server:
  port: 8082

spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: my-spring-client
            client-secret: 1oS9BFWRNcK2gZAVGITo4n8G7EITT97V
            scope: openid,profile,email
            redirect-uri: http://localhost:8082/login/oauth2/code/keycloak
        provider:
          keycloak:
            issuer-uri: http://localhost:8088/realms/my-app-realm

logging:
  level:
    org.springframework.security: DEBUG
